"""
Pydantic schemas for the CQIA application.
"""

from .base import (
    CQIA_BaseModel,
    CQIA_BaseCreate,
    CQIA_BaseUpdate,
    CQIA_BaseResponse,
    PaginatedResponse,
    ErrorResponse,
    SuccessResponse,
    HealthResponse,
)

from .user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserLogin,
    UserPasswordChange,
    UserPasswordResetRequest,
    UserPasswordReset,
    OrganizationBase,
    OrganizationCreate,
    OrganizationUpdate,
    OrganizationResponse,
    OrganizationMemberBase,
    OrganizationMemberCreate,
    OrganizationMemberUpdate,
    OrganizationMemberResponse,
    UserWithOrganizations,
)

from .project import (
    ProjectBase,
    ProjectCreate,
    ProjectUpdate,
    ProjectResponse,
    ProjectSummary,
    ProjectWebhookBase,
    ProjectWebhookCreate,
    ProjectWebhookUpdate,
    ProjectWebhookResponse,
    ProjectWithDetails,
    ProjectAnalysisTrigger,
    ProjectQualityMetrics,
)

from .analysis import (
    IssueBase,
    IssueCreate,
    IssueUpdate,
    IssueResponse,
    AnalysisArtifactBase,
    AnalysisArtifactCreate,
    AnalysisArtifactResponse,
    AnalysisBase,
    AnalysisCreate,
    AnalysisUpdate,
    AnalysisResponse,
    AnalysisWithDetails,
    AnalysisTrigger,
    AnalysisMetrics,
    AnalysisProgress,
    CodeAnalysisRequest,
    CodeAnalysisResponse,
)

from .report import (
    ReportTemplateBase,
    ReportTemplateCreate,
    ReportTemplateUpdate,
    ReportTemplateResponse,
    ReportBase,
    ReportCreate,
    ReportUpdate,
    ReportResponse,
    ReportWithDetails,
    ReportGenerationRequest,
    ReportGenerationResponse,
    ReportExportRequest,
    DashboardData,
    AnalyticsData,
    ReportMetrics,
    ReportFeedback,
)

from .conversation import (
    ConversationMessageBase,
    ConversationMessageCreate,
    ConversationMessageResponse,
    ConversationTemplateBase,
    ConversationTemplateCreate,
    ConversationTemplateUpdate,
    ConversationTemplateResponse,
    ConversationBase,
    ConversationCreate,
    ConversationUpdate,
    ConversationResponse,
    ConversationWithMessages,
    AIQueryRequest,
    AIQueryResponse,
    ConversationContext,
    AIInsightsRequest,
    AIInsightsResponse,
    CodeExplanationRequest,
    CodeExplanationResponse,
)

from .audit import (
    AuditLogBase,
    AuditLogCreate,
    AuditLogResponse,
    AuditLogArchiveBase,
    AuditLogArchiveResponse,
    AuditLogFilter,
    AuditLogSummary,
    AuditLogExportRequest,
    AuditLogExportResponse,
    AuditLogRetentionPolicy,
    AuditLogRetentionUpdate,
    AuditLogAlertRule,
    AuditLogAlertRuleCreate,
    AuditLogAlertRuleUpdate,
    AuditLogAlertRuleResponse,
    AuditLogAlert,
)

__all__ = [
    # Base schemas
    "CQIA_BaseModel",
    "CQIA_BaseCreate",
    "CQIA_BaseUpdate",
    "CQIA_BaseResponse",
    "PaginatedResponse",
    "ErrorResponse",
    "SuccessResponse",
    "HealthResponse",

    # User management
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserLogin",
    "UserPasswordChange",
    "UserPasswordResetRequest",
    "UserPasswordReset",
    "OrganizationBase",
    "OrganizationCreate",
    "OrganizationUpdate",
    "OrganizationResponse",
    "OrganizationMemberBase",
    "OrganizationMemberCreate",
    "OrganizationMemberUpdate",
    "OrganizationMemberResponse",
    "UserWithOrganizations",

    # Project management
    "ProjectBase",
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectSummary",
    "ProjectWebhookBase",
    "ProjectWebhookCreate",
    "ProjectWebhookUpdate",
    "ProjectWebhookResponse",
    "ProjectWithDetails",
    "ProjectAnalysisTrigger",
    "ProjectQualityMetrics",

    # Analysis and quality
    "IssueBase",
    "IssueCreate",
    "IssueUpdate",
    "IssueResponse",
    "AnalysisArtifactBase",
    "AnalysisArtifactCreate",
    "AnalysisArtifactResponse",
    "AnalysisBase",
    "AnalysisCreate",
    "AnalysisUpdate",
    "AnalysisResponse",
    "AnalysisWithDetails",
    "AnalysisTrigger",
    "AnalysisMetrics",
    "AnalysisProgress",
    "CodeAnalysisRequest",
    "CodeAnalysisResponse",

    # Reporting
    "ReportTemplateBase",
    "ReportTemplateCreate",
    "ReportTemplateUpdate",
    "ReportTemplateResponse",
    "ReportBase",
    "ReportCreate",
    "ReportUpdate",
    "ReportResponse",
    "ReportWithDetails",
    "ReportGenerationRequest",
    "ReportGenerationResponse",
    "ReportExportRequest",
    "DashboardData",
    "AnalyticsData",
    "ReportMetrics",
    "ReportFeedback",

    # AI Conversations
    "ConversationMessageBase",
    "ConversationMessageCreate",
    "ConversationMessageResponse",
    "ConversationTemplateBase",
    "ConversationTemplateCreate",
    "ConversationTemplateUpdate",
    "ConversationTemplateResponse",
    "ConversationBase",
    "ConversationCreate",
    "ConversationUpdate",
    "ConversationResponse",
    "ConversationWithMessages",
    "AIQueryRequest",
    "AIQueryResponse",
    "ConversationContext",
    "AIInsightsRequest",
    "AIInsightsResponse",
    "CodeExplanationRequest",
    "CodeExplanationResponse",

    # Audit and logging
    "AuditLogBase",
    "AuditLogCreate",
    "AuditLogResponse",
    "AuditLogArchiveBase",
    "AuditLogArchiveResponse",
    "AuditLogFilter",
    "AuditLogSummary",
    "AuditLogExportRequest",
    "AuditLogExportResponse",
    "AuditLogRetentionPolicy",
    "AuditLogRetentionUpdate",
    "AuditLogAlertRule",
    "AuditLogAlertRuleCreate",
    "AuditLogAlertRuleUpdate",
    "AuditLogAlertRuleResponse",
    "AuditLogAlert",
]
